### ISSUE TITLE
Facing 'FileNotFound' errors when diagnosing using Polyvore dataset

### ISSUE THREAD

**Issue by dk-github-acc** [WangXin93/fashion_compatibility_mcn#8]
Hi! I cloned this repo, and as mentioned I downloaded Polyvore dataset from https://github.com/gcucurull/visual-compatibility an placed the images folder in 'fashion_compatibility_mcn/data' directory. For IDs the json files from this repo is to be used so they're in 'data' directory with names like - 'test_no_dup_with_category_3more_name.json'

So I try to execute the cells within diagnosis.ipynb but I'm facing 'FileNotFound' error at next(iterator) stage after executing prepare_dataloaders() call. Many outfit ID directories are not found. 
Is there any processing of data involved with Polyvore dataset, so as to use it code from this repo?
Where am I going wrong? Please mention that and solve this issue.
Also please you make Polyvore-T dataset images available

![Screenshot from 2021-11-29 00-00-07](https://user-images.githubusercontent.com/53915310/143784675-0d4bda5a-f1f2-4925-972e-03ea1c79b368.png)

![Screenshot from 2021-11-29 00-00-13](https://user-images.githubusercontent.com/53915310/143784726-ad3438e5-ec96-45ab-8c97-2d042772d84c.png)

**Comment by ritikajha** [comment]
I am also facing the same issue.
Please help:(

**Comment by liuxx2016** [comment]
we also facing the same issue.
Could author release the your used Polyvore-T datasets, thanks. @WangXin93

**Comment by hyyuan123** [comment]
I also facing the same issue.

**Comment by WangXin93** [comment]
Hi, 

I download the **polyvore image dataset** from [this repository](https://github.com/xthan/polyvore-dataset), google address is [here](https://drive.google.com/file/d/0B4Eo9mft9jwoNm5WR3ltVkJWX0k/view?usp=sharing&resourcekey=0-U-30d1POF7IlnAE5bzOzPA), it is still available when I write this post.

As for the `FileNotFoundError`, here is how I ran the code: I ran the jupyter notebook in the `mcn` directory, and put the `images` directory in the `data` directory. If you run jupyter in another directory, you can specify the `root_dir='<your_path>/images/'` for the image path, and `data_dir=<your_path>/data'` in the line:

```python
# Dataloader
train_dataset, train_loader, val_dataset, val_loader, test_dataset, test_loader = prepare_dataloaders()
```

I hope this can help you successfully run the code .

Best Regard.

**Comment by dk-github-acc** [comment]
Thanks!
